--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."CLIENT";
DROP TABLE "SYSTEM"."COMMANDE";
DROP TABLE "SYSTEM"."EMPLOYE";
DROP TABLE "SYSTEM"."EQUIPEMENT";
DROP TABLE "SYSTEM"."FACTURE";
DROP TABLE "SYSTEM"."FOURNISSEURS";
DROP TABLE "SYSTEM"."GRADE";
DROP TABLE "SYSTEM"."INTERVENANT";
DROP TABLE "SYSTEM"."LOGIN";
DROP TABLE "SYSTEM"."PRODUIT";
DROP TABLE "SYSTEM"."RECLAMATION";
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(256 BYTE), 
	"PRENOM" VARCHAR2(256 BYTE), 
	"DATE_N" DATE, 
	"EMAIL" VARCHAR2(256 BYTE), 
	"NUM_TEL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COMMANDE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"CARB" VARCHAR2(256 BYTE), 
	"DATEE" VARCHAR2(256 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TELEPHONE" NUMBER, 
	"ID_GRADE" NUMBER, 
	"CARTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EQUIPEMENT" 
   (	"IDE" NUMBER, 
	"FONCTION" VARCHAR2(50 BYTE), 
	"MARKE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FACTURE" 
   (	"NUM_FACT" NUMBER, 
	"MONTANT" FLOAT(126), 
	"DATE_F" DATE, 
	"ID_CLIENT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FOURNISSEURS" 
   (	"NOM_SOCIETE" VARCHAR2(20 BYTE), 
	"NUMTEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRADE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GRADE" 
   (	"ID_G" NUMBER, 
	"SALAIRE" NUMBER, 
	"STATUT" VARCHAR2(20 BYTE), 
	"NB_HEURES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INTERVENANT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."INTERVENANT" 
   (	"ID" NUMBER, 
	"NUMERO" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOGIN" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PRODUIT" 
   (	"REFERANCE" NUMBER, 
	"PRIX" NUMBER, 
	"NOMPRODUIT" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" VARCHAR2(256 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RECLAMATION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"AMAIL" VARCHAR2(20 BYTE), 
	"ID_R" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CLIENT
SET DEFINE OFF;
Insert into SYSTEM.CLIENT (ID,NOM,PRENOM,DATE_N,EMAIL,NUM_TEL) values ('2','aya','souissi',to_date('01/01/00','DD/MM/RR'),'fnljhfnoure','0');
Insert into SYSTEM.CLIENT (ID,NOM,PRENOM,DATE_N,EMAIL,NUM_TEL) values ('1','amal','souissi',to_date('04/01/00','DD/MM/RR'),'sergdryhfrjtg','0');
REM INSERTING into SYSTEM.COMMANDE
SET DEFINE OFF;
REM INSERTING into SYSTEM.EMPLOYE
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYE (ID,NOM,PRENOM,DATE_NAISSANCE,EMAIL,TELEPHONE,ID_GRADE,CARTE) values ('2','zariat','SYSTEM',to_date('01/01/00','DD/MM/RR'),'jhsukhsz','153656','2',null);
Insert into SYSTEM.EMPLOYE (ID,NOM,PRENOM,DATE_NAISSANCE,EMAIL,TELEPHONE,ID_GRADE,CARTE) values ('3','zariat','ka',to_date('03/01/04','DD/MM/RR'),'kais.zariat@esprit.tn','32659884','1',null);
Insert into SYSTEM.EMPLOYE (ID,NOM,PRENOM,DATE_NAISSANCE,EMAIL,TELEPHONE,ID_GRADE,CARTE) values ('4','zar','yass',to_date('01/01/00','DD/MM/RR'),'line.zariat@esprit.tn','0','3','37:85:1B:AF');
Insert into SYSTEM.EMPLOYE (ID,NOM,PRENOM,DATE_NAISSANCE,EMAIL,TELEPHONE,ID_GRADE,CARTE) values ('1','zariat','line',to_date('01/01/00','DD/MM/RR'),'line.zariat@esprit.tn','12546321','2',null);
REM INSERTING into SYSTEM.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.FACTURE
SET DEFINE OFF;
Insert into SYSTEM.FACTURE (NUM_FACT,MONTANT,DATE_F,ID_CLIENT) values ('2','423534',to_date('02/01/21','DD/MM/RR'),'2');
REM INSERTING into SYSTEM.FOURNISSEURS
SET DEFINE OFF;
Insert into SYSTEM.FOURNISSEURS (NOM_SOCIETE,NUMTEL,ADRESSE) values ('hgghg ','123','hsjhgj');
REM INSERTING into SYSTEM.GRADE
SET DEFINE OFF;
Insert into SYSTEM.GRADE (ID_G,SALAIRE,STATUT,NB_HEURES) values ('2','102','secretair','8');
Insert into SYSTEM.GRADE (ID_G,SALAIRE,STATUT,NB_HEURES) values ('3','1000','inge','6');
Insert into SYSTEM.GRADE (ID_G,SALAIRE,STATUT,NB_HEURES) values ('1','1000','directeur','12');
REM INSERTING into SYSTEM.INTERVENANT
SET DEFINE OFF;
REM INSERTING into SYSTEM.LOGIN
SET DEFINE OFF;
Insert into SYSTEM.LOGIN (USERNAME,PASSWORD) values ('admin','admin');
REM INSERTING into SYSTEM.PRODUIT
SET DEFINE OFF;
REM INSERTING into SYSTEM.RECLAMATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENT_PK" ON "SYSTEM"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMMANDE_PK" ON "SYSTEM"."COMMANDE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYE_PK" ON "SYSTEM"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EQUIPEMENT_PK" ON "SYSTEM"."EQUIPEMENT" ("IDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FACTURE_PK" ON "SYSTEM"."FACTURE" ("NUM_FACT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FOURNISSEUR_PK" ON "SYSTEM"."FOURNISSEURS" ("NOM_SOCIETE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GRADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."GRADE_PK" ON "SYSTEM"."GRADE" ("ID_G") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INTERVENANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."INTERVENANT_PK" ON "SYSTEM"."INTERVENANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."LOGIN_PK" ON "SYSTEM"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PRODUIT_PK" ON "SYSTEM"."PRODUIT" ("REFERANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RECLAMATION_PK" ON "SYSTEM"."RECLAMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RECLAMATION_PK1" ON "SYSTEM"."RECLAMATION" ("ID_R") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("DATE_N" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("NUM_TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."COMMANDE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("TELEPHONE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("ID_GRADE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("IDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EQUIPEMENT" MODIFY ("IDE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EQUIPEMENT" MODIFY ("FONCTION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EQUIPEMENT" MODIFY ("MARKE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("NUM_FACT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."FACTURE" MODIFY ("NUM_FACT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FACTURE" MODIFY ("MONTANT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FACTURE" MODIFY ("DATE_F" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FACTURE" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("NOM_SOCIETE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."FOURNISSEURS" MODIFY ("NOM_SOCIETE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FOURNISSEURS" MODIFY ("NUMTEL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."FOURNISSEURS" MODIFY ("ADRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRADE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GRADE" ADD CONSTRAINT "GRADE_PK" PRIMARY KEY ("ID_G")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."GRADE" MODIFY ("ID_G" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INTERVENANT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."INTERVENANT" ADD CONSTRAINT "INTERVENANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."INTERVENANT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."INTERVENANT" MODIFY ("NUMERO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."INTERVENANT" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."INTERVENANT" MODIFY ("PRENOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("REFERANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PRODUIT" MODIFY ("REFERANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PRODUIT" MODIFY ("PRIX" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PRODUIT" MODIFY ("NOMPRODUIT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."PRODUIT" MODIFY ("DATE_ACHAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("ID_R")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."RECLAMATION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."RECLAMATION" MODIFY ("AMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."RECLAMATION" MODIFY ("ID_R" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."RECLAMATION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYE" ADD CONSTRAINT "IDGRADE" FOREIGN KEY ("ID_GRADE")
	  REFERENCES "SYSTEM"."GRADE" ("ID_G") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FACTURE" ADD CONSTRAINT "FK_CLIENT_FACT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "SYSTEM"."CLIENT" ("ID") ENABLE;
